### ISSUE TITLE
can't build on mac - missing 'python2' executable

### ISSUE THREAD

**Issue by pieper** [commontk/dcmjs#10]
Build fails by default because the executable is missing.

A workaround is:

$ ln -s /usr/bin/python2.7 /usr/local/bin/python2

**Comment by jcfr** [comment]
Closing. The updated build system now uses [dockcross-browser-asmjs](https://github.com/dockcross/dockcross#readme) and addresses all build issues providing a consistent build environment.

See here for updated instruction: https://github.com/commontk/dcmjs#building
