### ISSUE TITLE
second invocation of make causes new things to build

### ISSUE THREAD

**Issue by pieper** [commontk/dcmjs#11]
It's happened on two fresh builds now that I'll run make once and only the selected apps get built.

But then I'll run make again and a bunch of other apps, like the dicom networking apps, get built.

I suspect there's something wrong with the cmake code that enables and disables app building (BUILD_dcm*_APP).

**Comment by jcfr** [comment]
Closing. Following [build instructions](https://github.com/commontk/dcmjs#building), I am unable to reproduce using either `make` or `ninja`
