### ISSUE TITLE
Can't build on ubuntu 14.04

### ISSUE THREAD

**Issue by y5f** [commontk/dcmjs#13]
I installed the last version emscripten and did make -j5 like the given tutorial in the building section , but I'm ending up with a lot of errors in my CMakeFiles/CMakeError.log"  

[CMakeError.log.txt](https://github.com/commontk/dcmjs/files/369645/CMakeError.log.txt)

Please any help would very appreciated.

**Comment by jcfr** [comment]
Closing. The updated build system now uses [dockcross-browser-asmjs](https://github.com/dockcross/dockcross#readme)
