### ISSUE TITLE
File not found in node environment.

### ISSUE THREAD

**Issue by avandgard** [commontk/dcmjs#16]
Hey guys this is more a question than an issue. I am trying to use this solution in node.js server side application. I was able to build dcmjs.js but when I try to execute it with `node dcmjs.js dcmj2pnm x.dcm` it fails with an error "F: No such file or directory: reading file: x.dcm".

I've tried multiple variations like using absolute path, prefixing a path with './', moving file to file system root, executing in git-bash environment. But with no success.

In READEME.md there is a clause:
> Note that node executables do not have access to the local file system. To use dcmjs on a browser see the demos in the gh-pages branch.

But I did not found out how to pass the file to the environment where is the dcmjs.js executed.

Do you have any hints?

Thank you.

**Comment by pieper** [comment]
Hi Miroslav -

Thanks for testing this - the README is correct that this code can execute
in node, but cannot access the file system.  Being able to run dcmjs in
node is really just to test the build system.

I don't think running the emscripten generated code in node is a priority,
since it would always be possible to run the natively compiled dcmtk
executables if you are not in a browser.

-Steve

**Comment by avandgard** [comment]
Hi piper,

We actually ended using directly dcmtk executables. With dcmjs we hoped that we will not need to care about deployment platform. Now we are developing on windows machines but the app will be most probably deployed as a docker container to linux machines.

Maybe it will be worth to mention it in README a little bit more clearly that it is not mentioned to be used in node on server side.

Thx for quick response and clarification.

**Comment by pieper** [comment]
Hi Miroslav -

If you want to pursue the platform independent approach as a fallback then
it should be possible to use the node file system API to read buffers that
could be passed to dcmjs, but I suspect the performance would be pretty bad
compared to the native executables.

I added a note to the readme - good idea.

By the way a group of us are working on a pure-javascript dicom library if
that's a direction you are interested in.

-Steve

**Comment by SimonBiggs** [comment]
@avandgard if it is okay to include a python dependency pydicom is a great multiplatform dicom library.

@pieper is this work in progress pure dicom library up on GitHub? I am interested.

**Comment by pieper** [comment]
Yes, here's a very rough example page:

https://github.com/pieper/sites/tree/gh-pages/DICOMzero

And here's the implementation of the DICOM code:

https://github.com/pieper/sites/tree/gh-pages/dcmio

It's already pretty usable but there's not a lot of documentation or
examples yet.

The code is being developed as part of the QIICR project http://qiicr.org/

**Comment by SimonBiggs** [comment]
Thanks for this. I'm keen to make a web app front end for https://github.com/SimonBiggs/npgamma

The hope is that I'll be able to read RT-DICOM dose. I shall store this package away and take it for a spin in a month or so.

Thank you for all your hard work.

**Comment by SimonBiggs** [comment]
That looks amazing. Thanks.
