### ISSUE TITLE
Build errors with libxml2

### ISSUE THREAD

**Issue by fedorov** [commontk/dcmjs#17]
While building the project, I am getting a failure 

![image](https://user-images.githubusercontent.com/313942/42473705-57487ac6-8393-11e8-9bff-d826e3494826.png)

`LibXml2` build seems to have completed without errors, although there seems to be an error in `PNG`.

![image](https://user-images.githubusercontent.com/313942/42473690-4d36c560-8393-11e8-8ba3-b5db3d9ec682.png)

Is this project still maintained? Can someone help?

**Comment by jcfr** [comment]
Thanks for reporting the issue.

At Kitware, given some resources, we would be happy to help.

**Comment by fedorov** [comment]
I see. I don't have the resources though. Oh well!

**Comment by jcfr** [comment]
In the mean time, last time it ran, the build was successful in CircleCI. See https://circleci.com/gh/commontk/dcmjs/9

Did you run command list described in the README ? Also listed in [circle.yml](https://github.com/commontk/dcmjs/blob/master/circle.yml)

**Comment by fedorov** [comment]
Yes, I confirm I followed the instructions in the README, and I am trying to build the "as is" configuration of the project.

```shell
$ docker pull dockcross/browser-asmjs
$ docker run --rm dockcross/browser-asmjs > bin/dockcross-browser-asmjs
$ dockcross-browser-asmjs ninja -Cdcmjs-build
$ dockcross-browser-asmjs cmake -Bdcmjs-build -H. -GNinja
```

If only you included `dsr*` command line tools of DCMTK back in the days, I would not need to bother!

**Comment by fedorov** [comment]
Seems that libxml is only built in static mode

![image](https://user-images.githubusercontent.com/313942/42518443-d7af0c74-842f-11e8-9c9f-24b28f2b9c33.png)

**Comment by fedorov** [comment]
I confirmed that if I download the same libxml2 package and configure/build locally, I do get the shared library, but I do not know how to investigate as to why it does not work with the cmake/emscript magic.

![image](https://user-images.githubusercontent.com/313942/42519699-9d0240e8-8432-11e8-8887-7a1d1b503150.png)

**Comment by fedorov** [comment]
@pieper this is the issue I mentioned during the meeting this week.

**Comment by pieper** [comment]
> @pieper this is the issue I mentioned during the meeting this week.

Ah, yes, I see.  I haven't looked at this in a while.  I'm sure it's fixable but it's not clear how much effort would be involved.

**Comment by fedorov** [comment]
Right. For me, it is not even clear how to approach this.

For this project to be useful to me, I would need to add some more command line tools. But I cannot even get it to build out of the box. As far as I can tell from the exchange on this issue, the last time anyone built it successfully was CircleCI, 2 years ago: https://circleci.com/gh/commontk/dcmjs/9

**Comment by pieper** [comment]
Yes, that sounds about right.  The older binaries should still work but recompiling or extending to new tools isn't currently working.

I agree with your implication that the cmake build system and the emscripten toolchain make this task a challenge, which is why I'm not offering to take it on.  As you know that my current projects are more geared toward implementing [dicom native javascript](http://github.com/dcmjs-org) instead, so when time allows I put my effort there rather than in debugging this toolchain.

**Comment by jcfr** [comment]
Error reproduced in https://circleci.com/gh/commontk/dcmjs/11

**Comment by jcfr** [comment]
Closing. Fixed in https://github.com/commontk/dcmjs/commit/75c2d93461b6d70fe3c08eb5b039da97389a5dfb

**Comment by fedorov** [comment]
I've just checked, and indeed I confirm this issue is resolved!
