### ISSUE TITLE
libxml2 error on macOS

### ISSUE THREAD

**Issue by nark** [commontk/dcmjs#18]
Hello

I followed instructions from the wiki but I get an error when executing the following command :

    dockcross-browser-asmjs ninja -Cdcmjs-build

I get the following message :

    ninja: error: '/work/dcmjs-build/LibXml2/.libs/libxml2.so', needed by 'lib/libxml2dcm.so.3.6.1', missing and no known rule to make it
    FAILED: DCMTK-prefix/src/DCMTK-stamp/DCMTK-build
    cd /work/dcmjs-build/DCMTK-build && /usr/bin/cmake --build . && /usr/bin/cmake -E touch /work/dcmjs-build/DCMTK-prefix/src/DCMTK-stamp/DCMTK-build
    ninja: build stopped: subcommand failed.

What can I do to fix it ?

NB: I'm using macOS 10.13.6

Thx for your help.

**Comment by louismullie** [comment]
+1 same issue here

**Comment by fedorov** [comment]
Is this a duplicate of https://github.com/commontk/dcmjs/issues/17?

**Comment by jcfr** [comment]
Closing. Fixed in https://github.com/commontk/dcmjs/commit/75c2d93461b6d70fe3c08eb5b039da97389a5dfb
