### ISSUE TITLE
How to use this in NodeJS?

### ISSUE THREAD

**Issue by dbousamra** [commontk/dcmjs#27]
If I try:

`const dcm = require('./dcmjs/dcmjs')`

I get 

`Usage: /Users/dbousamra/Code/Projects/functor/src/dcm.js <appname> [options]`

Is there a recommended approach to using from NodejS?

**Comment by pieper** [comment]
We never really used it that way.  As you see in the readme, the node entry point is to call dcmtk executables.

It should be possible to change something in the main cpp code but I don't know what.

https://github.com/commontk/dcmjs/blob/master/src/dcmjs.cpp.in#L25


And FYI, we've been working on a pure-javascript alternative (https://github.com/dcmjs-org/dcmjs) to avoid the emscriptenized C++ code.

The new dcmjs is designed for either browser or nodejs environments.

https://github.com/dcmjs-org/dicomweb-server/blob/f32cde86bbda49ca26f53744bf5ec0421e8f2981/plugins/CouchDB.js#L5-L6

**Comment by dbousamra** [comment]
Thanks.

My eventual goal is to use the DICOM networking protocol. Does dcmjs have any plans for this? My current plan is to wrap DCMTK in some helper classes.

**Comment by pieper** [comment]
It's a good question with many angles.  As you probably know, traditional DICOM networking (a.k.a. DIMSE) is very widely used but can be tricky to deploy and debug (AETITLEs, port, transfer syntaxes, vendor differences, etc).  For that reason I think you are right to re-use DCMTK.

We do this in Slicer by using the dcmtk executables as subprocesses and the same could be done in node:

https://github.com/Slicer/Slicer/blob/master/Modules/Scripted/DICOMLib/DICOMProcesses.py

Or there's a pure-js dimse implementation that has been used a bit, but nowhere near as widely as dcmtk:

https://github.com/OHIF/dicom-dimse

The more modern (but way less common) version of DICOM networking is DICOMweb.  For this we use dcmjs/dicomweb-client and it should be fine on browser or node.  Of course it's also somewhat new and not widely tested.

https://github.com/dcmjs-org/dicomweb-client

Another thing you might consider is sticking to DICOMweb on the javascript side, and using an adaptor that speaks DIMSE, like this:

https://github.com/GoogleCloudPlatform/healthcare/tree/master/imaging/dicom_adapter

It all depends on exactly what you need to do and what you think will be easiest to support.

**Comment by jcfr** [comment]
This could help: https://github.com/fabiosantoscode/require-emscripten

It required some work to:
* really understand if it can help
* update the build system to leverage it

**Comment by jcfr** [comment]
See also https://github.com/emscripten-core/emscripten/issues/4032

**Comment by jcfr** [comment]
It turns out that we set `noInitialRun` to `1` only if `ENVIRONMENT_IS_WEB`

https://github.com/commontk/dcmjs/blob/5d4bf1c1917079dd052416f41d6fcd53d913ea9f/javascripts/pre.js#L6-L11

When running the module from the command line through nodejs, this means that the main function is executed.

This most likely explain what you observed.

**Comment by jcfr** [comment]
Other related issues is https://github.com/emscripten-core/emscripten/issues/2415 titled "Best way to tweak environment setup?". 

Note that support for this has recently been removed as it was not working well.

**Comment by jcfr** [comment]
## a possible way forward

To move forward with this, the we could always have `Module['noInitialRun'] = 1;` and explicitly call the `run` function.

This is implemented in https://github.com/commontk/dcmjs/pull/30

You can now do the following:

```js
require('./dcmjs').run(['appname', 'arg1'])
```

## more

Here are other things to explore:

* https://www.stevenengelhardt.com/2018/04/14/creating-umd-module-from-emscripten-using-cmake/

* https://github.com/emscripten-core/emscripten/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+UMD

* https://stackoverflow.com/questions/9146980/how-can-i-pass-a-variable-while-using-require-in-node-js
