### ISSUE TITLE
dcmsend can not open tcp connection

### ISSUE THREAD

**Issue by tarinitorpe** [commontk/dcmjs#31]
I build a dcm.js by myself, using Your description, I added the dcmsend during the build. But it is not working neither from cli and neither from browser. (If I am using the dcmsend from the installed dcmtk it works like charm) 
Other dcmtk apps are working well (I tried dcmodify and dcmdump and both are working in the browser and in the cli too...).

command:
node dcmjs.js dcmsend localhost 6666 /working/1.dcm 

This is the error message what I got for the above command :

Calling stub instead of signal()
F: cannot negotiate network association: Failed to establish association
F: 0006:0317 Peer aborted Association (or never connected)
F: 0006:031c TCP Initialization Error: Host is unreachable

Can You please give some hint about it?
My main goal is to make the dcmsend work in the browser.

**Comment by pieper** [comment]
Alas, traditional DICOM networking (DIMSE) can't work in the browser because there's no way to work with the regular sockets.

Please have a look at the discussion here for some alternatives:

https://github.com/commontk/dcmjs/issues/27#issuecomment-498061917

**Comment by jcfr** [comment]
To add more details, you may be interested in reading about use of networking socket in code compiler using emscripten. See https://emscripten.org/docs/porting/networking.html
