### ISSUE TITLE
Any on going work on this project?

### ISSUE THREAD

**Issue by arunjoshtech** [commontk/dcmjs#33]
Dear Team,
You are amazing team and doing greate for medical imaging through this project. My concern is there is no recent activities updates in the project. I request you all to do active development with need of the current scenario.
Great projects are done with small incremental improvement.

**Comment by pieper** [comment]
Most of the more recent development is going on in pure javascript here: https://github.com/dcmjs-org

This dcmtk port was an interesting and useful experiment, and could still be useful but I'm not sure how much it has been used in practice.  Do you have a use case for this that's not addressable with the javascript version?

**Comment by arunjoshtech** [comment]
Hi, I am sorry for the delay.
I am using our in-house developed pacs to receive ages from three of our X ray client images. Can I use your project as webserver to receive dicom ages from different dicom gateway ?

**Comment by pieper** [comment]
No, not this package since it is made for running in the browser where you don't have raw sockets available.  You could use [dcmjs-dimse](https://github.com/PantelisGeorgiadis/dcmjs-dimse) in node or [pynetdicom](https://github.com/pydicom/pynetdicom) to implement PACS gateways.
