### ISSUE TITLE
conflict with dcmtk in /usr/local/lib - can't find libc.h

### ISSUE THREAD

**Issue by pieper** [commontk/dcmjs#8]
On a mac with dcmtk installed via homebrew the emscripten build of dcmtk was finding ofstd headers from /usr/local/lib rather than the ones in DCMTK-build.  Uninstalling dcmtk from brew fixes this.

**Comment by craigmoodie** [comment]
Hello,

I installed dcmjs.js using the instructions on your page and it seemed to install properly. However, when I try to call it, I get a massive error output (below). Have you seen anything like this before and do you know how to debug it? I would appreciate the help.

Best,
Craig.

_______________________________________________________________________________

craig$ ./dcmjs.js
./dcmjs.js: line 1: syntax error near unexpected token `{Module["noInitialRun"]=1'
./dcmjs.js: line 1: `var ENVIRONMENT_IS_WEB=typeof window==="object";var Module=Module||{};if(ENVIRONMENT_IS_WEB){Module["noInitialRun"]=1;Module["noExitRuntime"]=1}var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function";var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(!ret&&filename!=nodePath["resolve"](filename)){filename=path.join(__dirname,"..","src",filename);ret=nodeFS["readFileSync"](filename)}if(ret&&!binary)ret=ret.toString();return ret};Module["readBinary"]=function readBinary(filename){return Module["read"](filename,true)};Module["load"]=function load(f){globalEval(read(f))};if(!Module["thisProgram"]){if(process["argv"].length>1){Module["thisProgram"]=process["argv"][1].replace(/\\/g,"/")}else{Module["thisProgram"]="unknown-program"}}Module["arguments"]=process["argv"].slice(2);if(typeof module!=="undefined"){module["exports"]=Module}process["on"]("uncaughtException",(function(ex){if(!(ex instanceof ExitStatus)){throw ex}}))}else if(ENVIRONMENT_IS_SHELL){if(!Module["print"])Module["print"]=print;if(typeof printErr!="undefined")Module["printErr"]=printErr;if(typeof read!="undefined"){Module["read"]=read}else{Module["read"]=function read(){throw"no read() available (jsc?)"}}Module["readBinary"]=function readBinary(f){if(typeof readbuffer==="function"){return new Uint8Array(readbuffer(f))}var data=read(f,"binary");assert(typeof data==="object");return data};if(typeof scriptArgs!="undefined"){Module["arguments"]=scriptArgs}else if(typeof arguments!="undefined"){Module["arguments"]=arguments}}else if(ENVIRONMENT_IS_WEB||ENVIRONMENT_IS_WORKER){Module["read"]=function read(url){var xhr=new XMLHttpRequest;xhr.open("GET",url,false);xhr.send(null);return xhr.responseText};if(typeof arguments!="undefined"){Module["arguments"]=arguments}if(typeof console!=="undefined"){if(!Module["print"])Module["print"]=function print(x){console.log(x)};if(!Module["printErr"])Module["printErr"]=function

**Comment by pieper** [comment]
You need to run
$ node dcmjs.js

By the way, this is unrelated to the original issue and should have been a new issue (no big deal, but just bookkeeping)

**Comment by craigmoodie** [comment]
Hi Pieper,

that actually was the problem! Thanks :)

**Comment by craigmoodie** [comment]
So now I'm getting a different error. I'm trying to run dcmdump, but I'm getting an error that suggests dcmjs can't find it:

$ node dcmjs.js dcmpdump
Unknown application name !
Usage: /Applications/dcmjs-build/dcmjs-build/bin/dcmjs.js <appname> [options]

**Comment by jcfr** [comment]
Hi Craig,

There is a typo in the name: "dcmdump" instead of "dcmpdump"

For more info, see https://github.com/commontk/dcmjs#usage

Hth
Jc

On Wed, Jun 24, 2015 at 12:51 PM, craigmoodie <notifications@github.com>
wrote:

> So now I'm getting a different error. I'm trying to run dcmdump, but I'm
> getting an error that suggests dcmjs can't find it:
>
> $ node dcmjs.js dcmpdump
> Unknown application name !
> Usage: /Applications/dcmjs-build/dcmjs-build/bin/dcmjs.js [options]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commontk/dcmjs/issues/8#issuecomment-114939744>.
>



-- 
+1 919 869 8849

**Comment by craigmoodie** [comment]
Well that was an easy fix! Thanks :)

**Comment by jcfr** [comment]
Closing. The updated build system now uses [dockcross-browser-asmjs](https://github.com/dockcross/dockcross#readme) and addresses all build issues providing a consistent build environment.

See here for updated instruction: https://github.com/commontk/dcmjs#building
